### ISSUE TITLE
Forking and License

### ISSUE THREAD

**Issue by ArmaanB** [palb91/dotfiles#1]
Hi there! I have been using your ZSH prompt for some time now, and am interested in publishing some changes which I have made to it. I noticed that this repo doesn't have a LICENSE or COPYING file, so I thought that it would be better to ask you first. I am thinking about using the MIT license for my fork of it, but if you would rather a different license, I could do that too. If you are okay with it, under what name should I credit you as the original author?

Thanks so much!

**Comment by palb91** [comment]
Hi !
First I'm glad to know that you like my work on the prompt and used it :) And thanks for asking.
To be honnest, I never thought about adding a licence to my dotfiles, but after your comment I will add one.
I will add the MIT LICENSE (seems to be a perfect non-restrictive license).
Regarding the name, you can use my full name "Pierre-Albéric TROUPLIN".

By the way I changed a few of my prompt, you may be interesting in the new changes.

**Comment by ArmaanB** [comment]
Thank you!

[Code is here in case you are interested](https://codeberg.org/armaan/admone)

I looked through and it turns out that not much of your original code was left, so I left you out of the MIT license, but kept you in the README. If after looking through it you would still like to be included in it, I would be happy to add you, but I think all that is actually left from your code is the code to add a new line above the prompt, and the code to tell the git branch.

Thank you again!

**Comment by palb91** [comment]
Yes, they look quite different and the similar pieces of code are mostly things that are available in the `man zsh` or many tutorials on the web.
I worked mostly on the function to shorten the path, I thought that you looked for that part, but it does not seem to appear in your prompt.
By the way, I just checked your work, there is a color reset that is not applied, the color of the first separator `]-[` is dark-grey while all of the other are the normal fg color. I don't think it is intended, so I suggest to remove the `%F{240}` at the line 35.
You could also consider not printing `-[]-` in case the block is empty ?

**Comment by ArmaanB** [comment]
Hi!

In response to the color thing, I believe that I fixed that at some point between when you commented this and now. 

I personally prefer the look of the empty boxes, so haven't implemented a way of removing them. Because the command output includes the formatting codes, I would have to pipe it through sed or awk to remove them.

Thanks!
